apiVersion: apps/v1
kind: Deployment
metadata:
  name: kingdomseekers-backend
  labels:
    app: kingdomseekers
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kingdomseekers
      tier: backend
  template:
    metadata:
      labels:
        app: kingdomseekers
        tier: backend
    spec:
      containers:
      - name: backend
        image: ${DOCKER_HUB_USERNAME}/kingdomseekers-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: NEON_DB_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        - name: NEON_DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: NEON_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kingdomseekers-backend
  labels:
    app: kingdomseekers
    tier: backend
spec:
  selector:
    app: kingdomseekers
    tier: backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP